<a href="https://colab.research.google.com/github/tusubirarita/My-Repo/blob/main/Workshop4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [4]:
type(data)

numpy.ndarray

In [5]:
data.ndim

1

In [6]:
data.size

3

In [7]:
data.shape

(3,)

In [8]:
data.dtype

dtype('int64')

In [9]:
#Creating a 2-D array with three rows and two columns
data_2d = np.array([[1,2],[3,4],[5,6]])
data_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
data_2d.ndim

2

In [11]:
data_2d.size

6

In [12]:
data_2d.shape

(3, 2)

In [13]:
data_2d.dtype

dtype('int64')

In [14]:
#Creating a 3-D array
data_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
data_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#1-D arrays
#Create an array with all data values initialised to one

In [15]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [16]:
ones.ndim

1

In [17]:
ones.size

3

In [18]:
ones.shape

(3,)

In [19]:
ones.dtype

dtype('float64')

In [20]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [21]:
#Create an array with values initialised using a random number generator
foo = np.random.random(3)
foo

array([0.85392249, 0.30987478, 0.7078905 ])

In [1]:
import numpy as np

In [22]:
#Uncomment and run the code cells below to answer the following questions.

In [23]:
#What is the number of dimensions of the foo array we created above?
foo.ndim

1

In [24]:
#What is the number of items (size) of the foo array?
foo.size

3

In [25]:
#What is the shape of the foo array?
foo.shape

(3,)

In [26]:
#What is the data type of the foo array?
foo.dtype

dtype('float64')

In [27]:

#Create an array of ten zeros.
data_zeros = np.array(10)

In [28]:

#Create an array of one million random numbers
data_random = np.random.random(1000000)

In [29]:
#2-D arrays
#By passing the shape of the desired array as the first parameter
#Create an array with three rows and two columns
ones_2d = np.ones((3,2))
ones_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
#Create an array with three rows and two columns
zeros_2d = np.zeros((3,2))
zeros_2d


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
#Create an array with three rows and two columns initialised by random numbers
bar = np.random.random((3,2))
bar

array([[0.47008428, 0.88170298],
       [0.34221245, 0.49976959],
       [0.89971288, 0.85706858]])

In [ ]:
#Exercise 2
#Create a 2-D array of random number with 1000 rows and 500 columns . check the values of the ndim, size, shape and dtype attributes


In [32]:
Ex_2 = np.random.random((1000,500))
Ex_2

array([[0.05369685, 0.00362899, 0.06106186, ..., 0.73490768, 0.98405967,
        0.82592983],
       [0.37007407, 0.43017004, 0.5039337 , ..., 0.25557314, 0.71238621,
        0.75430902],
       [0.57515699, 0.50378449, 0.10148782, ..., 0.12283522, 0.40409219,
        0.23746408],
       ...,
       [0.59911738, 0.3526584 , 0.02504156, ..., 0.36326439, 0.98321679,
        0.52913763],
       [0.44084267, 0.04689146, 0.77701124, ..., 0.38312973, 0.00493362,
        0.96738122],
       [0.06401534, 0.08740352, 0.8077326 , ..., 0.15781186, 0.02460654,
        0.69577849]])

In [33]:
Ex_2.ndim

2

In [34]:
Ex_2.dtype

dtype('float64')

In [35]:
Ex_2.shape

(1000, 500)

In [37]:
Ex_2.size

500000

In [ ]:
#Accessing elements of an array(indexing and slicing)

In [5]:
##Exercise
#Create a new 1-D array initialised with the data values [0,5,23,37,42,54,61,79,88,90]
data_new = np.array([0, 5, 23, 37, 42, 54, 61, 79, 88, 90])
data_new

array([ 0,  5, 23, 37, 42, 54, 61, 79, 88, 90])

In [ ]:
#What is the number of dimensions of the d